### PR TITLE
Allow to redefine calico node docker image name

### PR DESCRIPTION
**Pull request by SergK**
To have re-configurable CI and test calico code we need to have
an ability to add custom tags to calico node images, by default:
   NODE_CONTAINER_NAME=calico/node:latest

Other changes:
 * replace path `calico_node` to `$NODE_CONTAINER_DIR`
 * get rid of `pwd` command, instead we define SOURCE_DIR as
   the place where calico-containers code is located

### CODE REVIEW

**Comment by SergK** [comment]
@tomdee @neiljerram This change allows us to assign custom names (tags) to calico/node image, as the result we can run CI on not yep merged code and push to custom docker repositories,
for example by build some image we can set name:

`make node_image NODE_CONTAINER_NAME={custom-doker-repo}-calico/node-{pull_request_number}`

and as the result we can run different CI flows for exactly this custom image which can be identified for sure

**Comment by tomdee** [comment]
LGTM - @SergK Can you rebase then I can merge?

**Comment by SergK** [comment]
@tomdee sure, I will add also customizing calico/felix image. Thank you

**Comment by tomdee** [comment]
I'm happy with this change but waiting off merging it until semaphore fix their issue - https://twitter.com/semaphoreci/status/784518060547960834

**Comment by SergK** [comment]
@tomdee I've rebased on the latest changes, could you please check? Thank you

**Comment by tomdee** [comment]
LGTM - merging

**Pull request merged**
