### PR TITLE
export variables in startup.env, fixes #1208

### LINKED ISSUE #1208: IP is not being propagated to confd
```
Waiting for etcd connection...
No IP provided. Using detected IP: 10.10.25.14
bird: /etc/calico/confd/config/.bird.cfg856459999, line 5: syntax error
bird6: /etc/calico/confd/config/.bird6.cfg970370665, line 5: syntax error
Calico node started successfully
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
2016-10-12T16:33:16Z myhost confd[74]: INFO Backend set to etcd
2016-10-12T16:33:16Z myhost confd[74]: INFO Starting confd
2016-10-12T16:33:16Z myhost confd[74]: INFO Backend nodes set to https://one.main.etcd.in.pdx.cfdata.org:2379
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resources from confdir /etc/calico/confd
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird.toml.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6.toml.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6_aggr.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6_ipam.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird_aggr.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird_ipam.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Loading template resource from /etc/calico/confd/conf.d/tunl-ip.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/v1/ipam/v4
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/ipam/v2/host/myhost/ipv6/block
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/ipam/v2/host/myhost/ipv4/block
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/v1/ipam/v6
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/bgp/v1/global
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/bgp/v1
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/v1/ipam/v4
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/bgp/v1
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird_aggr.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird_aggr.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird6_ipam.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird6_ipam.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird_ipam.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird_ipam.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird_aggr.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird_aggr.cfg.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Retrieving keys from store
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Key prefix set to /calico/bgp/v1/global
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird6_ipam.cfg
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/config/bird6_ipam.cfg in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird_ipam.cfg
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/config/bird_ipam.cfg in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird_aggr.cfg
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/config/bird_aggr.cfg in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird6_aggr.cfg
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/config/bird6_aggr.cfg in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird.toml.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird.toml.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/tunl-ip.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/tunl-ip.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/conf.d/bird.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/conf.d/bird.toml in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /tmp/tunl-ip
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /tmp/tunl-ip in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird6.toml.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird6.toml.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/conf.d/bird6.toml
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Target config /etc/calico/confd/conf.d/bird6.toml in sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird6.cfg.mesh.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird6.cfg.mesh.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Using source template /etc/calico/confd/templates/bird.cfg.mesh.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Compiling source template /etc/calico/confd/templates/bird.cfg.mesh.template
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird.cfg
2016-10-12T16:33:16Z myhost confd[74]: INFO Target config /etc/calico/confd/config/bird.cfg out of sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Running bird -p -c /etc/calico/confd/config/.bird.cfg296712646
bird: /etc/calico/confd/config/.bird.cfg296712646, line 5: syntax error
2016-10-12T16:33:16Z myhost confd[74]: ERROR "bird: /etc/calico/confd/config/.bird.cfg296712646, line 5: syntax error\n"
2016-10-12T16:33:16Z myhost confd[74]: ERROR Config check failed: exit status 1
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird6.cfg
2016-10-12T16:33:16Z myhost confd[74]: INFO Target config /etc/calico/confd/config/bird6.cfg out of sync
2016-10-12T16:33:16Z myhost confd[74]: DEBUG Running bird6 -p -c /etc/calico/confd/config/.bird6.cfg586186349
bird6: /etc/calico/confd/config/.bird6.cfg586186349, line 5: syntax error
2016-10-12T16:33:16Z myhost confd[74]: ERROR "bird: /etc/calico/confd/config/.bird6.cfg586186349, line 5: syntax error\n"
2016-10-12T16:33:16Z myhost confd[74]: ERROR Config check failed: exit status 1
```

Line 5 looks like this:

```
router id ;
```

When I run the `node` container manually, I can see why `IP` is not being populated:

```
/ # python startup.py
Waiting for etcd connection...
No IP provided. Using detected IP: 10.10.25.14
/ # . startup.env
/ # /bin/sh -c 'echo $IP'

/ # export IP=$IP
/ # /bin/sh -c 'echo $IP'
10.36.25.14
```

In `/etc/rc.local`:

```
# Source any additional environment that was added by the startup script
. startup.env
```

These env variables (`IP` and `HOST`) are not propagated to `confd`.

### PR DESCRIPTION
**Pull request by bobrik**

### CODE REVIEW

**Comment by tomdee** [comment]
This is hitting space issues on semaphore - maybe rebasing would help.

**Comment by bobrik** [comment]
Semaphore is unhappy about a lots of things:

```
Error processing tar file(exit status 1): write /usr/share/doc/initramfs-tools/copyright: no space left on device
```

I rebased anyway.

**Comment by caseydavenport** [comment]
Most recent semaphore error is:

> c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

I believe this was fixed in https://github.com/projectcalico/calico-containers/pull/1215.  Sorry for the trouble, but I think you'll need one more rebase.

**Comment by lorenz** [comment]
Can we get this merged? I'm hitting the issue this PR addresses, the fix here works perfectly.

**Comment by tomdee** [comment]
@bobrik Thanks for this and sorry it's taking so long to get merged. I'm going to close it in favor of #1352 as that picks up another place where we should have the `export`

**Pull request closed without merging**
