### PR TITLE
Update policy-controller + calico/node version in k8s docs

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by djosborne** [comment]
@caseydavenport Code looks good, but does this need a runthrough test?

**Comment by caseydavenport** [comment]
@djosborne I don't think it needs a full test.  Might be worth someone running through the vagrant guide + stars demo or something to do a smoke test, but we shouldn't need to test _all_ of the guides.

@gunjan5 Care to run a quick Calico + Kubernetes test? I can help.

**Comment by gunjan5** [comment]
@caseydavenport : just saw the mention, I'll try it out when I get home

**Comment by gunjan5** [comment]
I tested it and it worked fine! LGTM :)

**Pull request merged**
