### PR TITLE
Add better IPv6 addr match check when starting node

### LINKED ISSUE #901: calicoctl node gives bad warning about IPv6
Using v0.18.0 I get a warning `WARNING: Could not confirm that the provided IPv6 address is assigned to this host.`
```
sudo ./calicoctl node --ip6 2001:0db8:0:f101::1 
Running Docker container with the following command:

docker run -d --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=gulfstream -e IP= -e IP6=2001:0db8:0:f101::1 -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico calico/node:v0.18.0

Calico node is running with id: 6450b9d2a4759316ba232a90925b9d32c896cda99860d24972e13d2edc87f045
Waiting for successful startup
No IP provided. Using detected IP: 172.18.18.200
WARNING: Could not confirm that the provided IPv6 address is assigned to this host.
Calico node started successfully
```

```
eth0      Link encap:Ethernet  HWaddr 08:00:27:bf:35:cd  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: 2001:db8:0:f101::1/64 Scope:Global
          inet6 addr: fe80::a00:27ff:febf:35cd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:523013 errors:0 dropped:0 overruns:0 frame:0
          TX packets:207537 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:479152024 (479.1 MB)  TX bytes:27554635 (27.5 MB)
```

### PR DESCRIPTION
**Pull request by TrimBiggs**
Fixes #901

### CODE REVIEW

**Comment by robbrockbank** [comment]
It looks fine, but I can't help thinking the get_host_ips() should really return a list of IPAddress objects.  Wonder if we should update it.  More work though.

**Comment by TrimBiggs** [comment]
I updated to reflect your comment, see the libcalico change https://github.com/projectcalico/libcalico/pull/105, which must be merged before this can be merged.

**Comment by robbrockbank** [comment]
You should grep the code for instances of get_host_ps.  We also use this in the ST utils class - that'll need fixing up.

**Comment by TrimBiggs** [comment]
I've updated this to fix the use of `get_host_ips` in `test_util.py`.

**Comment by robbrockbank** [comment]
LGTM

**Pull request merged**
