### PR TITLE
Add mtu configuration when creating veth, especially for ip-in-ip

### LINKED ISSUE #610: MTU within container not set to be equal to tunnel MTU
From titilambert:

Hello, I got a problem with MTU. MTU of container cali interface should be less or equal to the MTU of tunl0 interface. (I think the default is 1440)
Also, It should be cool, to be able to define the MTU when we create docker interface.
```
docker network create --driver=calico --opt nat-outgoing=true --opt ipip=true --mtu=1440 --subnet=192.168.1.0/24
```
Thanks !

### PR DESCRIPTION
**Pull request by TrimBiggs**
Fixes #610

### CODE REVIEW

**Comment by TrimBiggs** [comment]
This isn't how we should fix the issue.

**Comment by dudymas** [comment]
Can there be more of a description to why this PR was closed? I don't see why this solution is bad.

**Comment by robbrockbank** [comment]
@TrimBiggs Can you add some comments as to why this one was closed.  Ta.

**Comment by TrimBiggs** [comment]
This was originally closed because the backend design had not been fleshed out, so this piece did not make sense to go in without any configuration change being made to the containers.  We are working on designing a solution to this problem now.

**Comment by dudymas** [comment]
thanks for the feedback. I'm mostly affected by this once I start bridging edge nodes in Mantl.io

**Pull request closed without merging**
