### PR TITLE
Fix make targets for building ctl and node images

### PR DESCRIPTION
**Pull request by SergK**
* Fix `make node_image` target
* Apply the same changes to `make ctl_image` target

### CODE REVIEW

**Comment by SergK** [comment]
@tomdee could you please review?

**Comment by tomdee** [comment]
We've got a few other changes going in soon to this area - I'll take a look at this after they are merged

**Comment by SergK** [comment]
thank you, yes it seems in `golang-rebased` branch this issues is fixed

**Comment by SergK** [comment]
The issue was fixed

**Pull request closed without merging**
