### PR TITLE
Mock out modprobe calls in Unit Tests

### LINKED ISSUE #804: Unwanted output when running UTs
When I run the UTs I see
```
modprobe: can't change directory to '/lib/modules': No such file or directory
....modprobe: can't change directory to '/lib/modules': No such file or directory
.modprobe: can't change directory to '/lib/modules': No such file or directory
/usr/lib/python2.7/site-packages/docker/utils/utils.py:565: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.modprobe: can't change directory to '/lib/modules': No such file or directory
.modprobe: can't change directory to '/lib/modules': No such file or directory
.modprobe: can't change directory to '/lib/modules': No such file or directory

```
I imagine we're not mocking out something that we should be...

### PR DESCRIPTION
**Pull request by TrimBiggs**
Fixes #804

### CODE REVIEW

**Comment by tomdee** [comment]
Looks good and fixes the original bug. It would be nice to fix these other problems too (taken fro the circle ci output)
```
.........................................................................................................../usr/lib/python2.7/site-packages/docker/utils/utils.py:565: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
..................................................................................................................................
```
and 
```
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method Client.__del__ of <etcd.client.Client object at 0x7fd395c26c10>> ignored
```

**Comment by TrimBiggs** [comment]
I've fixed the `docker.utils.create_host_config()` issue as well, but I'm having trouble figuring out the TypeError problem with the etcd Client.

**Comment by TrimBiggs** [comment]
I've narrowed it down to having something to do with importing `connectors.client` into the `calicoctl` files that are tested, but I haven't been able to mock it out correctly to avoid the error.

**Comment by TrimBiggs** [comment]
@tomdee I think we should just get this in.  I don't think it's worth spending more time looking into that one remaining error at the moment.  I'll raise a low priority issue for it for now.

**Comment by TrimBiggs** [comment]
Raised UT `TypeError` as #810

**Comment by tomdee** [comment]
Sounds like a great plan. LGTM - merging.

**Pull request merged**
